### ISSUE TITLE
Reveal Error

### ISSUE THREAD

**Issue by IncompetenceQED** [robodair/UnofficialSpaceHulk#93]
I have yet to replicate this bug. A Space Marine turned South, revealing a 1 blip. Selecting the West button (the specific button probably doesn't matter) caused the Genestealer to reveal, and the Space Marine to turn West simultaneously. The Marine that saw the blip was still selected when it revealed the Genestealer and also turned West.
I don't know whether this happened at the same time, but there was a null reference error at Line 171 of the InputHandler class, meaning that selectedUnit must have been null.

Please see if you can replicate this error, because I have no idea where it possibly could have occurred.

**Comment by robodair** [comment]
Can't reproduce....
